descriptions:
  - "a person sitting"
  - "a person walking"
  - "a person running"
  - "a person picking up something"
  - "a person jumping"
  - "a person waving"
  - "a person smiling"
  - "a person moving"
